services:

  delta-db:
    build:
      context: ./backend/delta-table/docker
      dockerfile: Dockerfile
    #    build:
    #      context: ./backend/delta-table/docker/
    #      dockerfile: Dockerfile
    #user: "1001:1001"
    volumes:
      - ./backend/delta-table/data:/data
      - ./backend/delta-table/work-dir:/opt/spark/work-dir
      # - spark-workdir:/opt/spark/work-dir
    environment:
      - CLASSPATH=/opt/spark/jars/*
    ports:
      - "10000:10000"
      - "8888:8888"
    command:
    - sh
    - -c
    - |
      cd test
      ./run-tests.sh
