FROM pontusvisiongdpr/pv-deltadb:latest

# Switch to root to perform privileged operations
USER root

COPY delta-table/run-delta-jupyterlab.sh /usr/local/bin/db-init.sh
RUN chmod +x /usr/local/bin/db-init.sh

COPY delta-table/data /data
COPY delta-table/work-dir /opt/spark/work-dir


CMD ["/usr/local/bin/db-init.sh"]
