FROM pontusvisiongdpr/pv-deltadb:latest

# Copy init script
COPY backend/delta-table/run-delta-jupyterlab.sh /usr/local/bin/db-init.sh
RUN chmod +x /usr/local/bin/db-init.sh

# Copy data and work directories
COPY backend/delta-table/data /data
COPY backend/delta-table/work-dir /opt/spark/work-dir
