/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface AgGridReadReq {
    search?: PvpmartinsApi.AgGridInputSearch;
    cols?: PvpmartinsApi.AgGridInputSearchCols[];
    filters?: PvpmartinsApi.AgGridInputFilters[];
    dataType?: string;
    from?: number;
    to?: number;
    sortCol?: string;
    sortDir?: string;
}
