/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AgGridInputSearchCols {
    id?: string;
    name?: string;
    field?: string;
    sortable?: boolean;
    headerName?: string;
    filter?: boolean;
}
