/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface AgGridInputSearch {
    searchStr?: string;
    searchExact?: boolean;
    cols?: PvpmartinsApi.AgGridInputSearchCols[];
    extraSearch?: PvpmartinsApi.AgGridInputSearchExtraSearch;
}
