/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface AuthDeleteBody {
    dashboardId?: string;
    authGroups?: PvpmartinsApi.AuthGroups;
}
