/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface DashboardRef {
    /** Name of the dashboard */
    name?: string;
    /** Folder where the dashboard belongs */
    folder?: string;
    /** Owner of the dashboard */
    owner?: string;
    /** JSON containing all the dashboard state */
    state?: Record<string, unknown>;
}
