/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface DashboardCreateRes extends PvpmartinsApi.DashboardRef, PvpmartinsApi.BaseModelRef {
}
