/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface DashboardUpdateRes extends PvpmartinsApi.BaseModelRef, PvpmartinsApi.DashboardRef {
}
