/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface DashboardAuthGroup {
    /** Unique identifier of the dashboard */
    dashboardId?: string;
    dashboardName?: string;
    authGroups?: PvpmartinsApi.AuthGroups;
}
