/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface InlineResponse2001 {
    totalGroups?: number;
    authGroups?: PvpmartinsApi.AuthGroupRef[];
}
