/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface ReadPaginationFilter {
    from?: number;
    to?: number;
    filters?: Record<string, PvpmartinsApi.ReadPaginationFilterFilters>;
}
