/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface ReadPaginationFilterFiltersColIdCondition {
    dateFrom?: PvpmartinsApi.ReadPaginationFilterFiltersColIdConditionDateFrom;
    dateTo?: PvpmartinsApi.ReadPaginationFilterFiltersColIdConditionDateTo;
    filter?: PvpmartinsApi.ReadPaginationFilterFiltersColIdConditionFilter;
    filterTo?: PvpmartinsApi.ReadPaginationFilterFiltersColIdConditionFilterTo;
    filterType?: string;
    type?: string;
}
