"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableColumnRefKind = void 0;
exports.TableColumnRefKind = {
    Checkboxes: "checkboxes",
    Selectbox: "selectbox",
    Text: "text",
    Number: "number",
    Phone: "phone",
    Zipcode: "zipcode",
    Email: "email",
};
