/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface TableColumnRef {
    /** Unique identifier of the table column */
    id?: string;
    /** Name of the table column */
    name?: string;
    /** Field name of the table column */
    field?: string;
    /** Indicates if the table column is sortable */
    sortable?: boolean;
    /** Header name of the table column */
    headerName?: string;
    /** Indicates if the table column is filterable */
    filter?: boolean;
    /** Indicates the kind of column input */
    kind?: PvpmartinsApi.TableColumnRefKind;
}
