/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../..";
export interface TableRef {
    /** Name of the table */
    name?: string;
    label?: string;
    /** Table columns associated with the table */
    cols?: PvpmartinsApi.TableColumnRef[];
}
