openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /PontusTest/1.0.0/test/execute:
    post:
      operationId: pontus_executeQueryPOST
      tags:
        - Pontus
      parameters: []
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteQueryRes'
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: string
        '403':
          description: ''
          content:
            application/json:
              schema: {}
        '500':
          description: ''
          content:
            application/json:
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                params:
                  type: array
                  items:
                    type: string
                  nullable: true
              required:
                - query
components:
  schemas:
    ExecuteQueryRes:
      title: ExecuteQueryRes
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            additionalProperties: true
      required:
        - results
  securitySchemes: {}
