/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GroupUpdateReq {
    /** ID of the group to update */
    groupId?: string;
    /** Updated name of the group */
    name?: string;
    /** Updated parent groups of the group (optional) */
    parents?: string[];
    /** Updated symlinks associated with the group (optional) */
    symlinks?: string[];
}
