/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GroupCreateReq {
    /** Name of the group */
    name?: string;
    /** Parent groups of the group (optional) */
    parents?: string[];
    /** Symlinks associated with the group (optional) */
    symlinks?: string[];
}
