/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface NewUser {
    /** Name of the user */
    name?: string;
    /** IDs of the groups the user belongs to */
    authGroups?: string[];
}
