/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PvpmartinsApi from "../../../..";
export interface TableCreateReq {
    /**
     * Name of the table
     *
     */
    name: string;
    label: string;
    /** Table columns to be associated with the table during creation */
    cols: PvpmartinsApi.TableColumnRef[];
}
