/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UpdateUser {
    /** ID of the user to update */
    userId?: string;
    /** Updated name of the user */
    name?: string;
    /** Updated IDs of the groups the user belongs to */
    authGroups?: string[];
}
