/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgGridReadRes: core.serialization.ObjectSchema<serializers.AgGridReadRes.Raw, PvpmartinsApi.AgGridReadRes>;
export declare namespace AgGridReadRes {
    interface Raw {
        type?: string | null;
        from?: number | null;
        records?: string[] | null;
        to?: number | null;
        totalAvailable?: number | null;
    }
}
