/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgGridInputSearch: core.serialization.ObjectSchema<serializers.AgGridInputSearch.Raw, PvpmartinsApi.AgGridInputSearch>;
export declare namespace AgGridInputSearch {
    interface Raw {
        searchStr?: string | null;
        searchExact?: boolean | null;
        cols?: serializers.AgGridInputSearchCols.Raw[] | null;
        extraSearch?: serializers.AgGridInputSearchExtraSearch.Raw | null;
    }
}
