/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgGridInputFilters: core.serialization.ObjectSchema<serializers.AgGridInputFilters.Raw, PvpmartinsApi.AgGridInputFilters>;
export declare namespace AgGridInputFilters {
    interface Raw {
        colId?: string | null;
        filterType?: string | null;
        type?: string | null;
        filter?: string | null;
    }
}
