/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AgGridReadReq: core.serialization.ObjectSchema<serializers.AgGridReadReq.Raw, PvpmartinsApi.AgGridReadReq>;
export declare namespace AgGridReadReq {
    interface Raw {
        search?: serializers.AgGridInputSearch.Raw | null;
        cols?: serializers.AgGridInputSearchCols.Raw[] | null;
        filters?: serializers.AgGridInputFilters.Raw[] | null;
        dataType?: string | null;
        from?: number | null;
        to?: number | null;
        sortCol?: string | null;
        sortDir?: string | null;
    }
}
