/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AuthGroupRef: core.serialization.ObjectSchema<serializers.AuthGroupRef.Raw, PvpmartinsApi.AuthGroupRef>;
export declare namespace AuthGroupRef {
    interface Raw {
        groupId?: string | null;
        name?: string | null;
    }
}
