/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AuthGroups: core.serialization.ObjectSchema<serializers.AuthGroups.Raw, PvpmartinsApi.AuthGroups>;
export declare namespace AuthGroups {
    interface Raw {
        create?: string[] | null;
        read?: string[] | null;
        update?: string[] | null;
        delete?: string[] | null;
    }
}
