/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardUpdateRes: core.serialization.ObjectSchema<serializers.DashboardUpdateRes.Raw, PvpmartinsApi.DashboardUpdateRes>;
export declare namespace DashboardUpdateRes {
    interface Raw extends serializers.BaseModelRef.Raw, serializers.DashboardRef.Raw {
    }
}
