/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardReadRes: core.serialization.ObjectSchema<serializers.DashboardReadRes.Raw, PvpmartinsApi.DashboardReadRes>;
export declare namespace DashboardReadRes {
    interface Raw extends serializers.DashboardRef.Raw, serializers.BaseModelRef.Raw {
    }
}
