/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardsReadRes: core.serialization.ObjectSchema<serializers.DashboardsReadRes.Raw, PvpmartinsApi.DashboardsReadRes>;
export declare namespace DashboardsReadRes {
    interface Raw {
        totalDashboards?: number | null;
        dashboards?: serializers.Dashboard.Raw[] | null;
    }
}
