/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardgroupauthcreateAuthGroups: core.serialization.ObjectSchema<serializers.DashboardgroupauthcreateAuthGroups.Raw, PvpmartinsApi.DashboardgroupauthcreateAuthGroups>;
export declare namespace DashboardgroupauthcreateAuthGroups {
    interface Raw {
        create?: string[] | null;
        read?: string[] | null;
        update?: string[] | null;
        delete?: string[] | null;
    }
}
