/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardCreateReq: core.serialization.ObjectSchema<serializers.DashboardCreateReq.Raw, PvpmartinsApi.DashboardCreateReq>;
export declare namespace DashboardCreateReq {
    type Raw = serializers.DashboardRef.Raw;
}
