/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardDeleteReq: core.serialization.ObjectSchema<serializers.DashboardDeleteReq.Raw, PvpmartinsApi.DashboardDeleteReq>;
export declare namespace DashboardDeleteReq {
    type Raw = serializers.BaseModelRef.Raw;
}
