/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const DashboardReadReq: core.serialization.ObjectSchema<serializers.DashboardReadReq.Raw, PvpmartinsApi.DashboardReadReq>;
export declare namespace DashboardReadReq {
    type Raw = serializers.BaseModelRef.Raw;
}
