/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const InlineResponse2002: core.serialization.ObjectSchema<serializers.InlineResponse2002.Raw, PvpmartinsApi.InlineResponse2002>;
export declare namespace InlineResponse2002 {
    interface Raw {
        totalUsers?: number | null;
        users?: serializers.User.Raw[] | null;
    }
}
