/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const InlineResponse2001: core.serialization.ObjectSchema<serializers.InlineResponse2001.Raw, PvpmartinsApi.InlineResponse2001>;
export declare namespace InlineResponse2001 {
    interface Raw {
        totalGroups?: number | null;
        authGroups?: serializers.AuthGroupRef.Raw[] | null;
    }
}
