/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const MenuReadReq: core.serialization.ObjectSchema<serializers.MenuReadReq.Raw, PvpmartinsApi.MenuReadReq>;
export declare namespace MenuReadReq {
    interface Raw {
        id: string;
        path: string;
    }
}
