/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const MenuUpdateRes: core.serialization.ObjectSchema<serializers.MenuUpdateRes.Raw, PvpmartinsApi.MenuUpdateRes>;
export declare namespace MenuUpdateRes {
    type Raw = serializers.MenuItemTreeRef.Raw;
}
