/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const MenuReadRes: core.serialization.ObjectSchema<serializers.MenuReadRes.Raw, PvpmartinsApi.MenuReadRes>;
export declare namespace MenuReadRes {
    type Raw = serializers.MenuItemTreeRef.Raw;
}
