/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const MenuCreateRes: core.serialization.ObjectSchema<serializers.MenuCreateRes.Raw, PvpmartinsApi.MenuCreateRes>;
export declare namespace MenuCreateRes {
    interface Raw {
        id?: string | null;
        name?: string | null;
        kind?: string | null;
        path?: string | null;
        children?: serializers.MenuItemTreeRef.Raw[] | null;
    }
}
