/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilterFiltersFilterTo: core.serialization.Schema<serializers.ReadPaginationFilterFiltersFilterTo.Raw, PvpmartinsApi.ReadPaginationFilterFiltersFilterTo>;
export declare namespace ReadPaginationFilterFiltersFilterTo {
    type Raw = string | number;
}
