/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilterFiltersColIdConditionDateTo: core.serialization.Schema<serializers.ReadPaginationFilterFiltersColIdConditionDateTo.Raw, PvpmartinsApi.ReadPaginationFilterFiltersColIdConditionDateTo>;
export declare namespace ReadPaginationFilterFiltersColIdConditionDateTo {
    type Raw = string | string;
}
