/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilter: core.serialization.ObjectSchema<serializers.ReadPaginationFilter.Raw, PvpmartinsApi.ReadPaginationFilter>;
export declare namespace ReadPaginationFilter {
    interface Raw {
        from?: number | null;
        to?: number | null;
        filters?: Record<string, serializers.ReadPaginationFilterFilters.Raw> | null;
    }
}
