/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilterFiltersDateFrom: core.serialization.Schema<serializers.ReadPaginationFilterFiltersDateFrom.Raw, PvpmartinsApi.ReadPaginationFilterFiltersDateFrom>;
export declare namespace ReadPaginationFilterFiltersDateFrom {
    type Raw = string | string;
}
