/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilterFiltersFilter: core.serialization.Schema<serializers.ReadPaginationFilterFiltersFilter.Raw, PvpmartinsApi.ReadPaginationFilterFiltersFilter>;
export declare namespace ReadPaginationFilterFiltersFilter {
    type Raw = string | number;
}
