/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ReadPaginationFilterFiltersDateTo: core.serialization.Schema<serializers.ReadPaginationFilterFiltersDateTo.Raw, PvpmartinsApi.ReadPaginationFilterFiltersDateTo>;
export declare namespace ReadPaginationFilterFiltersDateTo {
    type Raw = string | string;
}
