/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const TableDataRowRef: core.serialization.Schema<serializers.TableDataRowRef.Raw, PvpmartinsApi.TableDataRowRef>;
export declare namespace TableDataRowRef {
    type Raw = Record<string, unknown>;
}
