/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const TableDataReadRes: core.serialization.ObjectSchema<serializers.TableDataReadRes.Raw, PvpmartinsApi.TableDataReadRes>;
export declare namespace TableDataReadRes {
    interface Raw {
        rowsCount?: number | null;
        rows?: serializers.TableDataRowRef.Raw[] | null;
    }
}
