/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const TablesReadResTablesItem: core.serialization.ObjectSchema<serializers.TablesReadResTablesItem.Raw, PvpmartinsApi.TablesReadResTablesItem>;
export declare namespace TablesReadResTablesItem {
    interface Raw extends serializers.BaseModelRef.Raw, serializers.TableRef.Raw {
    }
}
