/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const TableDataCreateRes: core.serialization.Schema<serializers.TableDataCreateRes.Raw, PvpmartinsApi.TableDataCreateRes>;
export declare namespace TableDataCreateRes {
    type Raw = serializers.TableDataRowRef.Raw;
}
