/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PvpmartinsApi from "../../../../api";
import * as core from "../../../../core";
export declare const User: core.serialization.ObjectSchema<serializers.User.Raw, PvpmartinsApi.User>;
export declare namespace User {
    interface Raw {
        userId?: string | null;
        name?: string | null;
        authGroups?: string[] | null;
    }
}
