"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PvpmartinsApiTimeoutError = void 0;
class PvpmartinsApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PvpmartinsApiTimeoutError.prototype);
    }
}
exports.PvpmartinsApiTimeoutError = PvpmartinsApiTimeoutError;
