/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthUpdateBody: core.serialization.Schema<serializers.AuthUpdateBody.Raw, PvpmartinsApi.AuthUpdateBody>;
export declare namespace AuthUpdateBody {
    interface Raw {
        dashboardId?: string | null;
        authGroups?: serializers.AuthGroups.Raw | null;
    }
}
