/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthCreateBody: core.serialization.Schema<serializers.AuthCreateBody.Raw, PvpmartinsApi.AuthCreateBody>;
export declare namespace AuthCreateBody {
    interface Raw {
        dashboardId?: string | null;
        authGroups?: serializers.DashboardgroupauthcreateAuthGroups.Raw | null;
    }
}
