/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const GroupDeleteReq: core.serialization.Schema<serializers.GroupDeleteReq.Raw, PvpmartinsApi.GroupDeleteReq>;
export declare namespace GroupDeleteReq {
    interface Raw {
        groupId?: string | null;
    }
}
