/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const GroupReadBody: core.serialization.Schema<serializers.GroupReadBody.Raw, PvpmartinsApi.GroupReadBody>;
export declare namespace GroupReadBody {
    interface Raw {
        groupId?: string | null;
    }
}
