/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const MenuDeleteReq: core.serialization.Schema<serializers.MenuDeleteReq.Raw, PvpmartinsApi.MenuDeleteReq>;
export declare namespace MenuDeleteReq {
    interface Raw {
        path: string;
        id: string;
    }
}
