/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const NewUser: core.serialization.Schema<serializers.NewUser.Raw, PvpmartinsApi.NewUser>;
export declare namespace NewUser {
    interface Raw {
        name?: string | null;
        authGroups?: string[] | null;
    }
}
