/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TableDataDeleteReq: core.serialization.Schema<serializers.TableDataDeleteReq.Raw, PvpmartinsApi.TableDataDeleteReq>;
export declare namespace TableDataDeleteReq {
    interface Raw {
        rowId: string;
        tableName: string;
    }
}
