/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TableDataUpdateReq: core.serialization.Schema<serializers.TableDataUpdateReq.Raw, PvpmartinsApi.TableDataUpdateReq>;
export declare namespace TableDataUpdateReq {
    interface Raw {
        tableName: string;
        rowId: string;
        cols?: serializers.TableDataRowRef.Raw | null;
    }
}
