/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PvpmartinsApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const UserReadBody: core.serialization.Schema<serializers.UserReadBody.Raw, PvpmartinsApi.UserReadBody>;
export declare namespace UserReadBody {
    interface Raw {
        userId?: string | null;
    }
}
