name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Services with Docker Compose
        run: |
          rm -rf ./backend/delta-table/work-dir/metastore_db
          rm -f ./backend/delta-table/work-dir/derby.log
          docker-compose up --build --abort-on-container-exit --exit-code-from app

      - name: Debug delta-db
        run: |
          docker-compose logs delta-db
          docker-compose exec delta-db ps aux
          docker-compose exec delta-db netstat -an | grep 10000

      - name: Tear Down
        if: always()
        run: |
          docker-compose down
