name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up --build -d

      - name: Netstat from delta-db
        run: |
          docker-compose exec delta-db sh -c "
            apt update
            apt install net-tools
            echo "checking port 10000"
            netstat -anp | grep 10000
          "

      - name: Wait for Services
        run: |
          docker-compose exec app sh -c "
          npm install;
          fern generate;
          cd delta-table/node/node-jdbc;
          npm install;
          cd ..;
          npm install;
          cd ../pontus-node-jdbc;
          npm run build;
          npm install;
          cd /usr/src/app;
          echo "Waiting for database...";
          timeout 22 sh -c 'until nc -z $0 $1; do sleep 1; done' delta-db 10000
          "

      - name: Start node app
        run: |
          docker-compose exec app sh -c "
            CLASSPATH=\$(ls /usr/src/app/delta-table/node/jars/* | xargs | sed -e 's/ /,/g');
            export CLASSPATH;
            echo 'CLASSPATH:' \$CLASSPATH;
            npm run build && node dist/src/server.js;
          "

      - name: Run Jest Tests with Debugging
        run: |
          docker-compose exec app sh -c "
            npm run jest -- --verbose --detectOpenHandles
          "

      - name: Tear Down
        if: always()
        run: |
          docker-compose down
