name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Clean up stale metastore files
        run: |
          rm -rf ./backend/delta-table/work-dir/metastore_db
          rm -f ./backend/delta-table/work-dir/derby.log

      - name: Start containers in detached mode
        run: |
          docker-compose up --build -d

      - name: Wait for delta-db to open port 10000
        run: |
          echo "Waiting for delta-db to open port 10000..."
          timeout 120 bash -c 'until docker exec $(docker ps -qf "name=delta-db") bash -c "nc -z localhost 10000"; do echo "Still waiting..."; sleep 2; done'
          echo "Port 10000 is open!"

      - name: Run tests
        run: |
          docker-compose exec app npm run test # or your app's entry command

      - name: Debug delta-db if needed
        if: failure()
        run: |
          echo "Logs from delta-db:"
          docker-compose logs delta-db
          echo "Running processes in delta-db:"
          docker-compose exec delta-db ps aux || true
          echo "Network status:"
          docker-compose exec delta-db netstat -an || true
          echo "Check port 10000:"
          docker-compose exec delta-db bash -c "nc -zv localhost 10000 || echo 'Port 10000 is NOT open'" || true

      - name: Tear Down
        if: always()
        run: docker-compose down -v

