name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: docker compose up -d delta-db

      - run: docker compose logs delta-db

      - run: |
          echo "Checking if delta-db port is open..."
          docker run --network container:$(docker ps -qf name=delta-db) busybox \
            sh -c 'nc -z localhost 10000 && echo "Port is open" || echo "Port is closed"'
