name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Start containers
        run: docker-compose up -d

      - name: Wait and debug delta-db
        run: |
          echo "Containers running:"
          docker ps -a

          echo "Checking logs for delta-db:"
          docker logs node-pontus-jdbc-db-setup

          echo "List files in data and work-dir:"
          ls -al ./backend/delta-table/data
          ls -al ./backend/delta-table/work-dir

          echo "Checking open ports inside container:"
          docker exec node-pontus-jdbc-db-setup netstat -tulnp || true
          
          echo "Checking Hive port 10000..."
          timeout 60 bash -c 'until nc -z delta-db 10000; do echo "Waiting..."; sleep 2; done; echo "Port is up!"'

