/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Pontus } from "./api/resources/pontus/client/Client";
export declare namespace PvpmartinsApiClient {
    interface Options {
        environment?: core.Supplier<environments.PvpmartinsApiEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
    }
}
export declare class PvpmartinsApiClient {
    protected readonly _options: PvpmartinsApiClient.Options;
    constructor(_options: PvpmartinsApiClient.Options);
    protected _pontus: Pontus | undefined;
    get pontus(): Pontus;
}
