"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PvpmartinsApiClient = void 0;
const Client_1 = require("./api/resources/pontus/client/Client");
class PvpmartinsApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get pontus() {
        var _a;
        return ((_a = this._pontus) !== null && _a !== void 0 ? _a : (this._pontus = new Client_1.Pontus(this._options)));
    }
}
exports.PvpmartinsApiClient = PvpmartinsApiClient;
