/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const PvpmartinsApiEnvironment: {
    readonly Default: "https://virtserver.swaggerhub.com";
};
export declare type PvpmartinsApiEnvironment = typeof PvpmartinsApiEnvironment.Default;
