"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PvpmartinsApiEnvironment = void 0;
exports.PvpmartinsApiEnvironment = {
    Default: "https://virtserver.swaggerhub.com",
};
